name: Deployment Pipeline

env:
  IS_COMMIT_WITH_SKIP: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}
  IS_MAIN_BRANCH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Run tests
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Create Render deployment
        if: ${{ env.IS_COMMIT_WITH_SKIP == false && env.IS_MAIN_BRANCH }}
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          node-version: lts/Jod #optional
          cli-version: 2.2.0 #optional

      - name: Notify Discord on Success
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ success() }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: info
          details: Build passed!

      - name: Notify Discord on Failure
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ failure() }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: error
          details: Build failed!

  tag_release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump patch version
        if: ${{ env.IS_COMMIT_WITH_SKIP == false && env.IS_MAIN_BRANCH }}
        uses: anothrNick/github-tag-action@1.64.0
        id: tag_version
        env:
          TAG_PREFIX: v
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Discord
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ success() }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: info
          details: Version updated!

      - name: Notify Discord on Failure
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ failure() }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: error
          details: Version bump failed!
