name: Testing stuff

on:
  push:
    branches:
      - main

env:
  CONDITION: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: condition
        run: echo  "$CONDITION"
